# Frontend Dockerfile
FROM node:20-alpine AS builder
WORKDIR /app
ARG VITE_SPRING_BOOT_API_URL=""
ENV VITE_SPRING_BOOT_API_URL=$VITE_SPRING_BOOT_API_URL
COPY package.json package-lock.json tsconfig.json vite.config.ts index.html ./
COPY src ./src
RUN npm ci && npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 3000
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]
